<form id="co-insurance-form" action="">
    <?php
        $insuranceRate = Mage::helper('insurance')->getRate();
        $isInsuranceChecked = Mage::helper('insurance')->isInsuranceEnabled();
    ?>
    <p class="control">
        <input type="checkbox" id="insurance" name="insurance" class="input-checkbox"
            <?php if($isInsuranceChecked):?>
                checked="checked"
            <?php endif;?>/>
        <label for="insurance"><strong><?php echo $this->__('Insurance Cost:');?></strong></label>
        <strong><?=$insuranceRate;?></strong>
    </p>
</form>


<div class="button-set">
    <div id="insurance-buttons-container">
        <button type="button" class="button validation-passed" onclick="insurance.save();"><span><?php echo $this->__('Continue') ?></span></button>
        <span id="insurance-please-wait" style="display:none;" class="opc-please-wait">
            <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" class="v-middle" alt="" /> &nbsp; <?php echo $this->__('Loading next step...') ?> &nbsp;
        </span>
    </div>
</div>

<script type="text/javascript">
    var Insurance = Class.create();
    Insurance.prototype = {
        initialize: function(form, saveUrl){
            this.form = form;
            if ($(this.form)) {
                $(this.form).observe('submit', function(event){this.save();Event.stop(event);}.bind(this));
            }
            this.saveUrl = saveUrl;
            this.onSave = this.nextStep.bindAsEventListener(this);
            this.onComplete = this.resetLoadWaiting.bindAsEventListener(this);
        },

        save: function(){
            if (checkout.loadWaiting!=false) return;

                 var validator = new Validation(this.form);
                 if (validator.validate()) {

                 checkout.setLoadWaiting('insurance');


                 var request = new Ajax.Request(
                 this.saveUrl,
                 {
                 method: 'post',
                 onComplete: this.onComplete,
                 onSuccess: this.onSave,
                 onFailure: checkout.ajaxFailure.bind(checkout),
                 parameters: Form.serialize(this.form)
                 }
                 );
             }
        },

        resetLoadWaiting: function(transport){
            checkout.setLoadWaiting(false);
        },

        nextStep: function(transport){
            if (transport && transport.responseText){
                try{
                    response = eval('(' + transport.responseText + ')');
                }
                catch (e) {
                    response = {};
                }
            }

            if (response.error) {
                if ((typeof response.message) == 'string') {
                    alert(response.message);
                } else {
                    if (window.billingRegionUpdater) {
                        billingRegionUpdater.update();
                    }

                    alert(response.message.join("\n"));
                }

                return false;
            }

            checkout.setStepResponse(response);
        }
    };

    var insurance = new Insurance('co-insurance-form', '<?php echo $this->getUrl('checkout/onepage/saveInsurance') ?>');


</script>